//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace Shrinklet.ShrinksterDotCom {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://shrinkster.com")]
    public class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebService() {
            this.Url = "http://www.shrinkster.com/WebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://shrinkster.com/ShrinkURL", RequestNamespace="http://shrinkster.com", ResponseNamespace="http://shrinkster.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ShrinkURL(string strURL) {
            object[] results = this.Invoke("ShrinkURL", new object[] {
                        strURL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginShrinkURL(string strURL, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ShrinkURL", new object[] {
                        strURL}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndShrinkURL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
